# Generated by Django 4.2.1 on 2023-05-26 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
