# Generated by Django 4.2.1 on 2023-06-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'permissions': (('can_add_data', 'can add a new data'),)},
        ),
    ]
