# Generated by Django 4.2.1 on 2023-06-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contacts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={},
        ),
    ]
